server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/digital_health?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
#    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  http:
    multipart:
      enable: false;
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/resources/mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

fhir:
  name: fhir-server
  url: https://smilecdr-uom2.comp90082-2023.vsbox.dev/fhir
  username: uom2-admin
  password: vojumosibaz#37
#  url: http://localhost:8084/fhir

common:
  basepath: /user_file/

email:
  username: CShowwww@gmail.com
  password: shsrfiurpnshlyrv
  subject: Notification from Virtual Doctor Platform
