server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  http:
    multipart:
      max-file-size: 10MB
      enable: false;
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379

fhir:
  name: fhir-server
  url: https://smilecdr-uom2.comp90082-2023.vsbox.dev/fhir
  username: uom2-admin
  password: vojumosibaz#37
#  url: http://localhost:8084/fhir

common:
  basepath: /user_file/

email:
  username: CShowwww@gmail.com
  password: shsrfiurpnshlyrv
  subject: Notification from Virtual Doctor Platform

keycloak:
  # ?????public?client
  public-client: true
  # keycloak???
  auth-server-url: https://keycloak-uom2.comp90082-2023.vsbox.dev/auth
  # keycloak??realm
  realm: master
  # client ID
  resource: Blue-ring-h1
  # ????
  securityConstraints:
    - securityCollections:
        - name: common user
          patterns:
            - /*
